name: Build-and-test

on: #[ push ]
  push:
    branches: 
     - master
#  workflow_dispatch:
   
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  

jobs:
  build:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    runs-on: ubuntu-latest
    steps:
    
    - run: ls -la
    
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: ls -la
    
    - name: Build
      run: go build -v ./...
    
    - run: ls -la
    - run: go run main.go
    
#     - name: Test
#       run: go test -v ./...
    
